### ISSUE TITLE
New feature: add logo to the center

### ISSUE THREAD

**Issue by Jenus** [Swiftify-Corp/IHProgressHUD#1]
Would SharedView instance be opened so that App can add logo to the center of Progress? 
Just like QR code with logo. 

Thanks

**Comment by Ibrahimhass** [comment]
You can show a QR code using the following technique            
Here the image View Size is set to 300 * 300 and the image file name is qr_code
```
IHProgressHUD.set(imageViewSize: CGSize.init(width: 300, height: 300))
IHProgressHUD.set(infoImage: UIImage.init(named: "qr_code")!.imageByMakingWhiteBackgroundTransparent()!)
IHProgressHUD.showInfowithStatus("Useful Information.")

```

Add the following image extension

```
extension UIImage {
    func imageByMakingWhiteBackgroundTransparent() -> UIImage? {
        
        let image = UIImage(data: UIImageJPEGRepresentation(self, 1.0)!)!
        let rawImageRef: CGImage = image.cgImage!
        
        let colorMasking: [CGFloat] = [222, 255, 222, 255, 222, 255]
        UIGraphicsBeginImageContext(image.size);
        
        let maskedImageRef = rawImageRef.copy(maskingColorComponents: colorMasking)
        UIGraphicsGetCurrentContext()?.translateBy(x: 0.0,y: image.size.height)
        UIGraphicsGetCurrentContext()?.scaleBy(x: 1.0, y: -1.0)
        UIGraphicsGetCurrentContext()?.draw(maskedImageRef!, in: CGRect.init(x: 0, y: 0, width: image.size.width, height: image.size.height))
        let result = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        return result
        
    }
}
```
Result:

![image](https://user-images.githubusercontent.com/16992520/52009208-5fd82180-24f8-11e9-9b45-1d2a95817e03.png)

Image Used:

![image](https://user-images.githubusercontent.com/16992520/52009236-754d4b80-24f8-11e9-99bc-9dd396bae4d7.png)

**Comment by Jenus** [comment]
Thanks for your quick response.

Possible my expression problem,  I really want to show the following effect:

![image](https://user-images.githubusercontent.com/1154625/52027364-20382680-2546-11e9-9a89-2b6157afb223.png)

That is:  progress is showing,  and a logo of app is positioning in the center of the Progress.
According to source code,  when progressing the image of the imageView reset to nil,  so could not keep the image when progressing.

**Comment by Ibrahimhass** [comment]
Ok, now I understand your requirement better would work on it and push to git. Will keep you posted on this thread. 

PS: if the image view for this static would it help you in your use case.
