### ISSUE TITLE
Main Thread Checker 

### ISSUE THREAD

**Issue by sprother** [Swiftify-Corp/IHProgressHUD#13]
If I drop the classes to the project without cocoapods,Main Thread Checker  interrupted the app when It was ran "IHProgressHUD.show()"

it was caused at "updateMotionEffectForOrientation(orientation)"

![屏幕快照 2019-12-11 上午9 58 34](https://user-images.githubusercontent.com/13460059/70584753-1028b300-1bfd-11ea-88d3-d53e9dcce25c.png)

animation issue
![IMG_4501](https://user-images.githubusercontent.com/13460059/70586107-33556180-1c01-11ea-91f6-66b6b2f04daa.jpg)

**Comment by Ibrahimhass** [comment]
Hi does this work fine when you use the project through CocoaPods?

**Comment by Ibrahimhass** [comment]
Fixed
