### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Gargo** [Swiftify-Corp/IHProgressHUD#17]
`let window : UIWindow = appDelegate.window! {`
In new xcode 11 projects `appDelegate.window == nil` because of using of scenes. Stop unwrap optionals via this incorrect way please. It is not the single project which has this issue

**Comment by kubacizek** [comment]
Download it from **pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'** . I had same problem.

**Comment by Ibrahimhass** [comment]
Thanks for pointing it out, this issue has now been fixed
