### ISSUE TITLE
support as a static framework

### ISSUE THREAD

**Issue by Jenus** [Swiftify-Corp/IHProgressHUD#2]
My project use new feature of cocoapod 1.5, [static framework ](http://blog.cocoapods.org/CocoaPods-1.5.0/). So the framework assets becomes as one part of main application.

when using as a static framework,  assets will load failed.  I will collect more detail soon.

**Comment by Jenus** [comment]
Sorry,  I make a retry,  it doesn't happen again.  Possible Xcode compiles the app partially.
Please ignore this issue,  thanks.

**Comment by Ibrahimhass** [comment]
Ok. I am closing this issue, then.
