### ISSUE TITLE
iOS13 uses scenedelegate and enable multiple windows

### ISSUE THREAD

**Issue by walletsh** [Swiftify-Corp/IHProgressHUD#20]
iOS13 uses scenedelegate and enable multiple windows. HUD is not in the center, but in the upper left corner.

**Comment by revg75** [comment]
Work around for progress hud not centering properly. Add this code to didFinishLaunchingWithOptions in AppDelegate
 if #available(iOS 13, *){
             self.window = UIWindow(frame: UIScreen.main.bounds)
 }
