### ISSUE TITLE
Crash when initializing IHProgressHud - Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by goransleko** [Swiftify-Corp/IHProgressHUD#23]
For example when I'm trying to create IHProgressHud in viewDidLoad() simply like this:

`DispatchQueue.global(qos: .utility).async {
            IHProgressHUD.show()
}`

Then the app crashes with the following error:

**Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/****/****/****/****/Pods/IHProgressHUD/IHProgressHUD/Classes/IHProgressHUD.swift, line 369**

The iOS deployment target is 13.0 and Swift 5 language.

**Comment by massimobio** [comment]
In your code you create a background thread to show the HUD.
UI work should always be done on the main thread. 
`viewDidLoad()` is called on the main thread so you can just call `IHProgressHUD.show()`

Also, are you on the latest version of IHProgressHUD? Use this in your podfile to get the latest:
`pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'`

**Comment by goransleko** [comment]
``

**Comment by goransleko** [comment]
Thank you! After changing pod from `pod 'IHProgressHUD'` to `pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'` the issue disappeared and everything works fine.
