### ISSUE TITLE
Type 'Bundle' has no member 'module'

### ISSUE THREAD

**Issue by aliawais** [Swiftify-Corp/IHProgressHUD#26]
App was compiling without any issues, after running 'pod install' using its master branch started having compilation error **"Type 'Bundle' has no member 'module'"** on two files:

- IHProgressHUD.swift
- IndefiniteAnimatedView.swft

In pod file I have
pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'

Also tried in a fresh app, same issue. But if I use **pod 'IHProgressHUD'** then it works fine.

How to solve the issue? I am using Xcode 11.7

**Comment by Ibrahimhass** [comment]
Hi this issue has been fixed
