### ISSUE TITLE
Can you please fix the completion handler for dismissWithDelay?

### ISSUE THREAD

**Issue by sbrighiu** [Swiftify-Corp/IHProgressHUD#29]
When completion is used inside completionBlock, the completion parameter is nil, making so that dismissWithDelay trailing completion block is not called

**Comment by Ibrahimhass** [comment]
It seems to work just fine.

```
self.view.backgroundColor = .blue
IHProgressHUD.show()
IHProgressHUD.dismissWithDelay(10.0, completion: {
    self.view.backgroundColor = .red
})
```

Please let me know if I do not get your issue correctly
