### ISSUE TITLE
Testing on iPhone Xs Device causes a "Main Thread Checker" exception.

### ISSUE THREAD

**Issue by TwitchedDesign** [Swiftify-Corp/IHProgressHUD#4]
The issue from this topic still isn't solved. https://github.com/Swiftify-Corp/IHProgressHUD/issues/3 

iPhone XS Running on IOS 12.2 get the same error. 

> Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
> PID: 9428, TID: 3268605, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

**Comment by Ibrahimhass** [comment]
I think this is an issue with Apple please check this [SO post](https://stackoverflow.com/a/54607871/5807290).
