### ISSUE TITLE
Layout in iOS 13 messed up

### ISSUE THREAD

**Issue by heysaik** [Swiftify-Corp/IHProgressHUD#7]
When presenting the HUD, the layout does not appear in the center, rather it appears in the to left corner. This issue has begun ever since Beta 7

**Comment by harjeetk** [comment]
Yes i am facing the same issue related to this.

**Comment by IshuRocks** [comment]
I'm facing the same issue related to this.

**Comment by PranjalDudhe** [comment]
I'm facing the same issue related to this.

**Comment by Ibrahimhass** [comment]
Can you please share a screenshot I tested the code recently using Xcode 11.4 and iOS simulator and it happens to run just fine. Maybe this issue has been fixed please try installing with the latest commit by:

pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'

**Comment by aidev1065** [comment]
This occurs only when you use Apple's new SceneDelegate and enable Multiple Windows. Also try to use a real device and not a simulator

**Comment by revg75** [comment]
Work around for progress hud not centering properly. Add this code to didFinishLaunchingWithOptions in AppDelegate
if #available(iOS 13, *){
self.window = UIWindow(frame: UIScreen.main.bounds)
}

**Comment by IMKalpataru** [comment]
> Work around for progress hud not centering properly. Add this code to didFinishLaunchingWithOptions in AppDelegate
> if #available(iOS 13, *){
> self.window = UIWindow(frame: UIScreen.main.bounds)
> }

This is working.
