### ISSUE TITLE
Unexpected duplicate tasks - iOS 13 - Xcode 11

### ISSUE THREAD

**Issue by sbrighiu** [Swiftify-Corp/IHProgressHUD#9]
Hi,

I wanted to update our apps to iOS 13 and archiving it fails with errors like:

Unexpected duplicate tasks:
1) Target 'IHProgressHUD' (project 'Pods') has copy command from '.../Pods/IHProgressHUD/IHProgressHUD/Classes/IHProgressHUD.bundle/error@2x.png' to '.../Library/Developer/Xcode/DerivedData/Animest-bpcsmwfbgjyhfvebytrdskxkoder/Build/Intermediates.noindex/ArchiveIntermediates/Animest Dev/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/IHProgressHUD.framework/error@2x.png'
2) Target 'IHProgressHUD' (project 'Pods') has copy command from '.../Pods/IHProgressHUD/IHProgressHUD/Classes/IHProgressHUD.bundle/error@2x.png' to '.../Library/Developer/Xcode/DerivedData/Animest-bpcsmwfbgjyhfvebytrdskxkoder/Build/Intermediates.noindex/ArchiveIntermediates/Animest Dev/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/IHProgressHUD.framework/error@2x.png'

The fix is simple and can be done easily. Just untick the target membership box for the items, and tick it back on.

If you can fix this fast so I can start my pipelines for release today, I would appreciate it very much.

PS: more info link, https://stackoverflow.com/questions/52384152/xcode-10-unexpected-duplicate-task-copyplistfile

**Comment by sbrighiu** [comment]
@Ibrahimhass

**Comment by bhushanbafana** [comment]
getting same issue please check the issue as early as possible, so i can upload the app.

@Ibrahimhass

**Comment by narlei** [comment]
+ 1

**Comment by dfeler** [comment]
I am also having this issue, please fix this as soon as possible

**Comment by omarojo** [comment]
+1

**Comment by sbrighiu** [comment]
I’ve updated Cocoapods to the latest version and it seems to be fixed now. Try it :) it may just be a hiccup.

--------------------------------------
Stefan Brighiu
Software Engineer @ AB4 Systems
Phone: +40 744 581 921
Web: http://ab4.systems

**Comment by narlei** [comment]
I've updated Cocoapods, try update gems... but still the same problem:

This is only with **New Build System**

````
Unexpected duplicate tasks:
1) Target 'IHProgressHUD' (project 'Pods') has copy command from '/app-ios/Pods/IHProgressHUD/IHProgressHUD/Classes/IHProgressHUD.bundle/info@3x.png' to '/Users/xx/Library/Developer/Xcode/DerivedData/MyApp-gzdqbugguohnkhdzzsdvsiatbckl/Build/Products/Debug-iphoneos/IHProgressHUD/IHProgressHUD.framework/info@3x.png'
2) Target 'IHProgressHUD' (project 'Pods') has copy command from '/app-ios/Pods/IHProgressHUD/IHProgressHUD/Classes/IHProgressHUD.bundle/info@3x.png' to '/Users/xx/Library/Developer/Xcode/DerivedData/MyApp-gzdqbugguohnkhdzzsdvsiatbckl/Build/Products/Debug-iphoneos/IHProgressHUD/IHProgressHUD.framework/info@3x.png'
````

**Comment by narlei** [comment]
I created a pull request with the fix and swift 5 
https://github.com/Swiftify-Corp/IHProgressHUD/pull/10

**Comment by Ibrahimhass** [comment]
@narlei merged the pull request

**Comment by Gargo** [comment]
@Ibrahimhass 
I have the same issue xcode 11.3.1, swift 5 - imported with cocoapods, nothing was fixed.
NOTE: it fails on archiving.

**Comment by georgenimber** [comment]
any update?

**Comment by alexgoodison** [comment]
Managed to fix it using the solution from: https://stackoverflow.com/a/60181503

`File -> Workspace Settings -> Change New Build System to Legacy`

**Comment by jamesdhope** [comment]
Other pods are failing with the same error. Changing to Legacy Build System is less than ideal.

**Comment by progn** [comment]
Change `pod 'IHProgressHUD'` to

```pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'```

in Podfile

**Comment by syedwshah** [comment]
Go to "Compile Sources" & "Copy Bundle resources" in Build Phases. If you see the same file within both of those drop downs, remove the file from "Copy Bundle resources". Clean build, and run!

**Comment by Parmendravyshor** [comment]
when i installed video_360 plugin given an error



Running pod install...                                           2,953ms
Running Xcode build...                                                  
Xcode build done.                                            8.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/2w/wbrqydfn5p99d1zxkr9l2bvm0000gn/T/flutter_tools.ghbOeE/flutter_ios_build_temp_dirgbxFeq/temporary_xcresul
        t_bundle

    note: Building targets in dependency order
    error: Unexpected duplicate tasks
        note: Target 'video_360' (project 'Pods') has copy command from
        '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty36
        0Player/Swifty360Player-Info.plist' to '/Users/itx/Downloads/artist_replugged-master 2
        2/build/ios/Debug-iphonesimulator/video_360/video_360.framework/Swifty360Player-Info.plist'
        note: Target 'video_360' (project 'Pods') has copy command from
        '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty36
        0Player/Swifty360Player-Info.plist' to '/Users/itx/Downloads/artist_replugged-master 2
        2/build/ios/Debug-iphonesimulator/video_360/video_360.framework/Swifty360Player-Info.plist'
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99.
    (in target 'FirebaseMessaging' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'GoogleDataTransport' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'FirebaseCoreDiagnostics' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'Mux-Stats-AVPlayer' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'FMDB' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'FirebaseInstallations' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99.
    (in target 'FirebaseAuth' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'nanopb' from project 'Pods')
    warning: no rule to process file
    '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty360Pla
    yer/Swifty360Player.modulemap' of type 'sourcecode.module-map' for architecture 'arm64' (in target 'video_360' from
    project 'Pods')
    warning: no rule to process file
    '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty360Pla
    yer/Swifty360Player.debug.xcconfig' of type 'text.xcconfig' for architecture 'arm64' (in target 'video_360' from project
    'Pods')
    warning: no rule to process file
    '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty360Pla
    yer/Swifty360Player.release.xcconfig' of type 'text.xcconfig' for architecture 'arm64' (in target 'video_360' from
    project 'Pods')
    warning: no rule to process file
    '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty360Pla
    yer/Swifty360Player.modulemap' of type 'sourcecode.module-map' for architecture 'x86_64' (in target 'video_360' from
    project 'Pods')
    warning: no rule to process file
    '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty360Pla
    yer/Swifty360Player.debug.xcconfig' of type 'text.xcconfig' for architecture 'x86_64' (in target 'video_360' from project
    'Pods')
    warning: no rule to process file
    '/Users/itx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_360-0.0.8/ios/Classes/Swifty360Player/Swifty360Pla
    yer/Swifty360Player.release.xcconfig' of type 'text.xcconfig' for architecture 'x86_64' (in target 'video_360' from
    project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'FirebaseCoreInternal' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'GoogleUtilities' from project 'Pods')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase
    "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase
    "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'FirebaseCore' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99.
    (in target 'Firebase' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'GTMSessionFetcher' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'Mux-Stats-Core' from project 'Pods')
    /Users/itx/Downloads/artist_replugged-master 2 2/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in
    target 'PromisesObjC' from project 'Pods')

    Result bundle written to path:
        /var/folders/2w/wbrqydfn5p99d1zxkr9l2bvm0000gn/T/flutter_tools.ghbOeE/flutter_ios_build_temp_dirgbxFeq/temporary_xcresul
        t_bundle


Error (Xcode): Unexpected duplicate tasks


Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.

**Comment by syedwshah** [comment]
Mobile dev problems… 🤔

You may change development target from Xcode. As per issues with
dependencies…

You can try a clean build after attempting a reinstall of packages:

Delete your node_modules and reinstall your packages.

From project root:
npx pod-install
yarn or npm

CMD + K May run clean build on Xcode.

Good luck 🍀

**Comment by BrahimChouih** [comment]
@Parmendravyshor I have the same error with the same package. Is there any solution for this problem?
